package ORMroad;

// Generated 18.03.2015 1:22:07 by Hibernate Tools 3.4.0.CR1

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import java.util.HashSet;
import java.util.Set;

/**
 * Station generated by hbm2java
 */
@XmlRootElement(name = "station")
@XmlAccessorType(XmlAccessType.FIELD)
public class Station implements java.io.Serializable {

	private Integer stationId;
	private String name;
	private Set waypoints = new HashSet(0);

	public Station() {
	}

	public Station(String name) {
		this.name = name;
	}

	public Station(String name, Set waypoints) {
		this.name = name;
		this.waypoints = waypoints;
	}

	public Integer getStationId() {
		return this.stationId;
	}

	public void setStationId(Integer stationId) {
		this.stationId = stationId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getWaypoints() {
		return this.waypoints;
	}

	public void setWaypoints(Set waypoints) {
		this.waypoints = waypoints;
	}

}
